# Generated by Django 3.1.2 on 2020-10-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='moviemodel',
            table='movie',
        ),
    ]
