# Generated by Django 3.1.2 on 2020-10-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201004_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='title',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AlterModelTable(
            name='moviemodel',
            table=None,
        ),
    ]
