# Generated by Django 3.1.2 on 2020-10-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201004_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviemodel',
            options={'verbose_name': 'фільм', 'verbose_name_plural': 'фільми'},
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
