# Generated by Django 3.1.2 on 2020-10-04 15:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='RatingModel',
        ),
        migrations.RenameField(
            model_name='ratingmodel',
            old_name='str',
            new_name='star',
        ),
    ]
